### ISSUE TITLE
OpenAPI definition has $ref to #/components/schemas/URL for responseObjects

### ISSUE THREAD

**Issue by MikeRalphson** [RumbleDiscovery/rumble-api#3]
For example:

https://github.com/RumbleDiscovery/rumble-api/blob/7dde73580df5f68aaaed0df37f365f447c53e6d3/rumble-api.yml#L1284

This should probably look like:

```yaml
      responses:
        '200':
          description: task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URL'
```

but I'm not familiar with your API. There are several instances of direct `$refs` to schemas instead of responseObjects.

**Comment by hdm** [comment]
Hi @MikeRalphson! that is intentional, those responses are objects with the schema specified.
